os: Visual Studio 2017
version: '2.5.7.{build}'
skip_tags: true
install:
- ps: |
    $full_build = Test-Path env:GHFVS_KEY
    git submodule init
    git submodule sync

    if ($full_build) {
      $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
      $fileContent += $env:GHFVS_KEY.Replace(' ', "`n")
      $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
      Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent
    } else {
      git submodule deinit script
    }

    git submodule update --recursive --force
    nuget restore GitHubVS.sln
build_script:
- ps: scripts\build.ps1 -AppVeyor -BuildNumber:$env:APPVEYOR_BUILD_NUMBER
test_script:
- cmd: nunit3-console "C:\projects\visualstudio\test\GitHub.Api.UnitTests\bin\Release\net461\GitHub.Api.UnitTests.dll" "C:\projects\visualstudio\test\GitHub.App.UnitTests\bin\Release\net461\GitHub.App.UnitTests.dll" "C:\projects\visualstudio\test\GitHub.Exports.Reactive.UnitTests\bin\Release\net461\GitHub.Exports.Reactive.UnitTests.dll" "C:\projects\visualstudio\test\GitHub.Exports.UnitTests\bin\Release\net461\GitHub.Exports.UnitTests.dll" "C:\projects\visualstudio\test\GitHub.Extensions.UnitTests\bin\Release\net461\GitHub.Extensions.UnitTests.dll" "C:\projects\visualstudio\test\GitHub.InlineReviews.UnitTests\bin\Release\net461\GitHub.InlineReviews.UnitTests.dll" "C:\projects\visualstudio\test\GitHub.TeamFoundation.UnitTests\bin\Release\net461\GitHub.TeamFoundation.UnitTests.dll" "C:\projects\visualstudio\test\GitHub.UI.UnitTests\bin\Release\net461\GitHub.UI.UnitTests.dll" "C:\projects\visualstudio\test\GitHub.VisualStudio.UnitTests\bin\Release\net461\GitHub.VisualStudio.UnitTests.dll" "C:\projects\visualstudio\test\MetricsTests\MetricsTests\bin\Release\MetricsTests.dll" "C:\projects\visualstudio\test\TrackingCollectionTests\bin\Release\net461\TrackingCollectionTests.dll" --where "cat != Timings" --result=myresults.xml;format=AppVeyor --trace=Verbose
on_success:
- ps: |
    if ($full_build) {
      script\Sign-Package -AppVeyor
    }
on_finish:
- ps: scripts\Run-CodeCoverage.ps1 -AppVeyor -Configuration:Release
- IF NOT "%BCC_TOKEN%x"=="x" %USERPROFILE%\.nuget\packages\bcc-msbuildlog\0.0.2-alpha\tools\net471\BCC.MSBuildLog.exe -i output.binlog -o checkrun.json -c "%APPVEYOR_BUILD_FOLDER%"
- IF NOT "%BCC_TOKEN%x"=="x" %USERPROFILE%\.nuget\packages\bcc-submission\0.0.2-alpha\tools\net471\BCC.Submission.exe -i checkrun.json -t "%BCC_TOKEN%" -h "%APPVEYOR_REPO_COMMIT%"
